export const fragrances=[
 {id:'rose-velvet',name:'Rose Velvet',family:'Floral',collection:'Women',price:599,image:0,notes:['Rose petals','Lychee','Soft vanilla'],description:'A soft rose opening with a sweet, velvety finish.',concentration:'Extrait de Parfum',best:true},
 {id:'golden-bloom',name:'Golden Bloom',family:'Floral',collection:'Women',price:549,image:1,notes:['Pear','White jasmine','Golden musk'],description:'Fresh flowers warmed by a gentle touch of golden musk.',concentration:'Eau de Parfum',best:true},
 {id:'amber-veil',name:'Amber Veil',family:'Amber',collection:'Unisex',price:699,image:2,notes:['Bergamot','Amber','Vanilla woods'],description:'Warm amber and creamy woods, quietly captivating.',concentration:'Extrait de Parfum',best:true},
 {id:'pure-musk',name:'Pure Musk',family:'Fresh',collection:'Unisex',price:499,image:3,notes:['White tea','Cotton blossom','Clean musk'],description:'An airy, close-to-skin fragrance for everyday moments.',concentration:'Eau de Parfum',best:true},
 {id:'noir-woods',name:'Noir Woods',family:'Woody',collection:'Men',price:799,image:4,notes:['Black pepper','Cedar','Smoked amber'],description:'Deep woods with a smooth, subtly smoky character.',concentration:'Extrait de Parfum',best:true},
 {id:'citrus-muse',name:'Citrus Muse',family:'Citrus',collection:'Unisex',price:449,image:5,notes:['Mandarin','Neroli','Light cedar'],description:'A bright citrus breeze that feels like a fresh beginning.',concentration:'Eau de Parfum',best:true},
 {id:'petal-silk',name:'Petal Silk',family:'Floral',collection:'Women',price:579,image:0,notes:['Peony','Rose water','Cashmere musk'],description:'Dewy petals and a soft, delicate trail.',concentration:'Eau de Parfum'},
 {id:'sunlit-neroli',name:'Sunlit Neroli',family:'Citrus',collection:'Unisex',price:529,image:1,notes:['Orange blossom','Neroli','White woods'],description:'Radiant orange blossom with an easy, luminous feel.',concentration:'Eau de Parfum'},
 {id:'velvet-amber',name:'Velvet Amber',family:'Amber',collection:'Unisex',price:749,image:2,notes:['Pink pepper','Amber resin','Tonka'],description:'Rich amber softened by a gentle, creamy warmth.',concentration:'Extrait de Parfum'},
 {id:'moonlit-linen',name:'Moonlit Linen',family:'Fresh',collection:'Unisex',price:479,image:3,notes:['White tea','Iris','Sheer musk'],description:'Quiet freshness, like clean linen at the end of the day.',concentration:'Eau de Parfum'},
 {id:'ebony-oud',name:'Ebony Oud',family:'Woody',collection:'Men',price:849,image:4,notes:['Cardamom','Oud accord','Sandalwood'],description:'A smooth, woody statement with a warm finish.',concentration:'Extrait de Parfum'},
 {id:'rose-nocturne',name:'Rose Nocturne',family:'Floral',collection:'Women',price:649,image:0,notes:['Dark rose','Plum','Amber musk'],description:'Rose after dusk: a little richer, a little more mysterious.',concentration:'Extrait de Parfum'}
].map((product,index)=>({...product,photo:{src:index<6?'/assets/perfume-atlas.webp':'/assets/catalog-extras-v2.webp',frame:index<6?index:index-6},homePhoto:{src:'/assets/home-signatures-v2.webp',frame:index%6}}));
export const initialJournal=[
 {slug:'finding-your-signature-scent',title:'Finding your signature scent',date:'2026-09-24T09:00:00.000Z',category:'Scent Stories',excerpt:'Follow the notes you love, then give a fragrance time to tell its story.',image:'/assets/hero-perfume.webp',published:true,body:'## Start with what you already love\nA cup of white tea, the warmth of vanilla, a fresh bouquet. Familiar aromas are a useful starting point when exploring fragrance.\n\n## Meet the fragrance slowly\nTry one scent at a time. Notice the opening, then return to it after it has settled. Your favorite part may arrive later.\n\n## Make it personal\nThere is no single perfect choice for everyone. Choose the fragrance you enjoy wearing, and let your collection grow with your days.'},
 {slug:'a-guide-to-fragrance-notes',title:'A little guide to fragrance notes',date:'2026-09-20T09:00:00.000Z',category:'Scent Guide',excerpt:'From the first impression to the lingering finish, discover the layers in a bottle.',image:'/assets/atelier-story.webp',published:true,body:'## The first impression\nTop notes introduce a fragrance. They often feel bright and immediately noticeable.\n\n## The heart of the scent\nAs the opening softens, heart notes become more apparent. Florals, gentle spices and aromatic notes often give a scent its character.\n\n## The lasting impression\nBase notes create depth. Woods, amber and musk can feel warmer and more settled. The way you experience these layers will vary from person to person.'},
 {slug:'small-rituals-for-everyday-fragrance',title:'Small rituals, beautiful everyday moments',date:'2026-09-16T09:00:00.000Z',category:'Everyday Rituals',excerpt:'Turn a familiar morning into a small moment that belongs to you.',image:'/assets/hero-perfume.webp',published:true,body:'## A moment before the day begins\nChoose a fragrance that suits your mood. A light citrus can feel bright; a soft musk can feel calm and familiar.\n\n## Keep it considered\nStart lightly and adjust to your preference. Be mindful of shared spaces and other people around you.\n\n## Enjoy the ritual\nA favorite scent can be a personal finishing touch. Keep your bottle somewhere you will remember to enjoy it.'},
 {slug:'choosing-a-thoughtful-fragrance-gift',title:'Choosing a thoughtful fragrance gift',date:'2026-09-12T09:00:00.000Z',category:'Gifting',excerpt:'A few thoughtful questions can make a fragrance gift feel wonderfully personal.',image:'/assets/atelier-story.webp',published:true,body:'## Think about their favorites\nDo they enjoy fresh florals, warm woods or a clean, understated scent? Their existing favorites can offer helpful clues.\n\n## Choose the mood\nConsider whether the gift is for everyday wear, a special evening or a new chapter. Keep the recipient at the center of the choice.\n\n## Add a personal note\nTell them why you chose it. If you need help exploring the collection, send our studio an inquiry.'},
 {slug:'inside-the-aurea-studio',title:'Inside the Auréa fragrance studio',date:'2026-09-08T09:00:00.000Z',category:'Behind the Bottle',excerpt:'A look at the colors, textures and quiet inspiration behind our collection.',image:'/assets/atelier-story.webp',published:true,body:'## Inspired by the everyday\nSoft silk, fresh petals and the golden light of late afternoon inform the mood of Auréa. Each concept begins with a feeling we want to capture.\n\n## A collection of contrasts\nOur fragrance concepts range from airy citrus and white musk to warm amber and deeper woods. We believe there is room for more than one signature.\n\n## Your next chapter\nExplore the collection and tell us which notes speak to you. The best place to begin is with a little curiosity.'}
].map((entry,index)=>({...entry,image:'/assets/journal-faq-v2.webp#frame='+index}));
