import {initialJournal,fragrances} from './data.mjs';
import {renderPage} from './templates.mjs';
const json=(value,status=200)=>new Response(JSON.stringify(value),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
const legacyCovers=['/assets/hero-perfume.webp','/assets/atelier-story.webp'];
const covers=[...legacyCovers,...initialJournal.map(entry=>entry.image)];
const pathFor=slug=>'content/journal/'+slug+'.json';
const safePath=path=>/^content\/journal\/[a-z0-9][a-z0-9-]{0,99}\.json$/.test(path);
async function seed(db){const done=await db.prepare("SELECT value FROM editor_settings WHERE key='journal_seeded'").first();if(done)return;await db.batch([...initialJournal.map(entry=>db.prepare("INSERT OR IGNORE INTO journal_entries(path,raw,updated_at) SELECT ?,?,? WHERE NOT EXISTS(SELECT 1 FROM editor_settings WHERE key='journal_seeded')").bind(pathFor(entry.slug),JSON.stringify(entry),new Date().toISOString())),db.prepare("INSERT OR IGNORE INTO editor_settings(key,value) VALUES('journal_seeded','1')")]);}
function presentJournalRow(row){const data=JSON.parse(row.raw);const original=initialJournal.find(entry=>pathFor(entry.slug)===row.path);if(original&&legacyCovers.includes(data.image))data.image=original.image;return {data:JSON.stringify(data),file:{path:row.path,id:row.path}};}
async function entries(db){await seed(db);const result=await db.prepare('SELECT path,raw FROM journal_entries ORDER BY updated_at DESC').all();return result.results.map(presentJournalRow);}
async function publicEntries(db){return (await entries(db)).map(entry=>JSON.parse(entry.data)).filter(entry=>entry.published!==false).sort((a,b)=>new Date(b.date)-new Date(a.date));}
async function editor(request,env){let id=request.headers.get('oai-authenticated-user-id');let email=request.headers.get('oai-authenticated-user-email');if(env.LOCAL_PREVIEW===true){id='local-preview-editor';email='editor@aurea.local';}if(!id)throw Object.assign(new Error('Sign in as the site owner to use the Journal editor.'),{status:401});await env.DB.prepare("INSERT OR IGNORE INTO editor_settings(key,value) VALUES('editor_user_id',?)").bind(id).run();const account=await env.DB.prepare("SELECT value FROM editor_settings WHERE key='editor_user_id'").first();if(account?.value!==id)throw Object.assign(new Error('This Journal has one assigned editor account.'),{status:403});return {name:'Auréa Journal Editor',login:id,email:email||'',token:''};}
function writeOrigin(request){const origin=request.headers.get('Origin');if(origin!==new URL(request.url).origin)throw Object.assign(new Error('Please submit from this website.'),{status:403});if(!request.headers.get('Content-Type')?.includes('application/json'))throw Object.assign(new Error('JSON input is required.'),{status:415});}
async function input(request){const raw=await request.text();if(raw.length>35000)throw Object.assign(new Error('The request is too large.'),{status:413});try{return JSON.parse(raw);}catch{throw Object.assign(new Error('Invalid request data.'),{status:400});}}
function validArticle(raw,path){if(!safePath(path))throw new Error('Invalid Journal path.');const entry=JSON.parse(raw);entry.slug=path.split('/').pop().replace(/\.json$/,'');if(typeof entry.title!=='string'||entry.title.length<3||entry.title.length>140||typeof entry.excerpt!=='string'||entry.excerpt.length>500||typeof entry.body!=='string'||entry.body.length>25000||!Number.isFinite(new Date(entry.date).getTime())||!covers.includes(entry.image))throw new Error('Please complete the title, date, excerpt, cover and article.');entry.published=entry.published!==false;entry.category=String(entry.category||'Scent Stories').slice(0,60);return JSON.stringify(entry);}
async function api(request,env,url){const db=env.DB;if(!db)throw new Error('Database binding is unavailable.');
 if(url.pathname==='/api/journal'&&request.method==='GET')return json({entries:await publicEntries(db)});
 if(url.pathname.startsWith('/api/editor/')){const account=await editor(request,env);if(url.pathname==='/api/editor/session')return json(account);if(url.pathname==='/api/editor/entries'&&request.method==='GET')return json({entries:await entries(db)});if(url.pathname==='/api/editor/entry'&&request.method==='GET'){const path=url.searchParams.get('path');if(!safePath(path||''))return json({error:'Invalid path'},400);await seed(db);const row=await db.prepare('SELECT path,raw FROM journal_entries WHERE path=?').bind(path).first();return row?json(presentJournalRow(row)):json({error:'Article not found'},404);}if(url.pathname==='/api/editor/media')return json({media:covers.map(path=>({name:path.split('/').pop(),id:path,path,url:path,displayURL:path}))});
 writeOrigin(request);const body=await input(request);
 if(url.pathname==='/api/editor/entry'&&request.method==='POST'){await seed(db);if(!Array.isArray(body.dataFiles)||body.dataFiles.length!==1)return json({error:'Save one Journal entry at a time.'},400);const file=body.dataFiles[0];try{const path=file.newPath||file.path;const raw=validArticle(file.raw,path);const writes=[db.prepare('INSERT INTO journal_entries(path,raw,updated_at) VALUES(?,?,?) ON CONFLICT(path) DO UPDATE SET raw=excluded.raw,updated_at=excluded.updated_at').bind(path,raw,new Date().toISOString())];if(file.newPath&&file.path!==file.newPath&&safePath(file.path))writes.push(db.prepare('DELETE FROM journal_entries WHERE path=?').bind(file.path));await db.batch(writes);return json({ok:true});}catch(error){return json({error:error.message},400);}}
 if(url.pathname==='/api/editor/entries'&&request.method==='DELETE'){if(!Array.isArray(body.paths)||!body.paths.length||body.paths.length>10||body.paths.some(path=>!safePath(path)))return json({error:'Invalid Journal paths.'},400);await seed(db);await db.batch(body.paths.map(path=>db.prepare('DELETE FROM journal_entries WHERE path=?').bind(path)));return json({ok:true});}return json({error:'Editor action not available.'},404);}
 if(url.pathname==='/api/inquiries'&&request.method==='POST'){writeOrigin(request);const body=await input(request);if(body.website)return json({ok:true,message:'Thank you for your inquiry.'});const name=String(body.name||'').trim(),email=String(body.email||'').trim().toLowerCase(),message=String(body.message||'').trim(),interest=String(body.interest||'');if(name.length<2||name.length>80||email.length>120||!/^\S+@\S+\.\S+$/.test(email)||message.length<10||message.length>2000||body.consent!==true||![...fragrances.map(p=>p.id),'recommendation','gift-selection','delivery'].includes(interest))return json({error:'Please complete all fields and agree to share your inquiry details.'},400);const recent=await db.prepare('SELECT COUNT(*) AS count FROM inquiries WHERE email=? AND created_at>?').bind(email,new Date(Date.now()-3600000).toISOString()).first();if(recent.count>=3)return json({error:'Please wait before sending another inquiry.'},429);const now=new Date().toISOString();await db.batch([db.prepare('INSERT INTO inquiries(id,name,email,interest,message,created_at) VALUES(?,?,?,?,?,?)').bind(crypto.randomUUID(),name,email,interest,message,now),db.prepare('INSERT INTO inquiry_actions(id,action,page,created_at) VALUES(?,?,?,?)').bind(crypto.randomUUID(),'form_submission','/contact',now)]);return json({ok:true,message:'Thank you. Your inquiry has been saved for this prototype’s site owner.'},201);}
 if(url.pathname==='/api/actions'&&request.method==='POST'){writeOrigin(request);const body=await input(request);if(body.action!=='contact_button_click'||typeof body.page!=='string'||!/^\/[a-z0-9/-]*$/.test(body.page))return json({error:'Invalid action.'},400);await db.prepare('INSERT INTO inquiry_actions(id,action,page,created_at) VALUES(?,?,?,?)').bind(crypto.randomUUID(),body.action,body.page,new Date().toISOString()).run();return json({ok:true});}return json({error:'Action not found.'},404);
}
export default {async fetch(request,env,ctx){const url=new URL(request.url);try{if(url.pathname.startsWith('/api/'))return await api(request,env,url);if(request.method!=='GET'&&request.method!=='HEAD')return new Response('Method not allowed',{status:405});const path=url.pathname.length>1?url.pathname.replace(/\/$/,''):url.pathname;if(path==='/'||path==='/journal'||path.startsWith('/journal/')){const content=renderPage(path,await publicEntries(env.DB),url.origin);if(content)return new Response(request.method==='HEAD'?null:content,{headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'}});}else {const content=renderPage(path,[],url.origin);if(content)return new Response(request.method==='HEAD'?null:content,{headers:{'Content-Type':'text/html; charset=utf-8','X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin'}});}if(path.startsWith('/journal/'))return new Response('This scent story is not available.',{status:404});return await env.ASSETS.fetch(request);}catch(error){return json({error:error.status?error.message:'The request could not be completed. Please try again.'},error.status||500);}}};
